### ISSUE TITLE
Request for rationale

### ISSUE THREAD

**Issue by luciotato** [djc/runa#1]
Hi! It seems interesting, but the documentation is so sparse that I can't tell!

Can you write a "rationale", i.e. extend "A Python-like systems programming language" with use-cases, advantages, etc.  Something in the style of http://clojure.org/rationale

I've been working on my own lang also, compiling to js and C. It is called "LiteScript" and is like having the javascript core (dynamic+prototypal inh.+higher order fns) _but_ with python-like "indentation is significant" and proper classes. Check it at: https://github.com/luciotato/LiteScript

**Comment by luciotato** [comment]
You can also add comments to your code, it will help others and yourself, when re-reading old code. I've been reading your code, and comment will help a lot.... example: at https://github.com/djc/runa/blob/master/runac/tokenizer.py

```
def tokenize(f):  # tokenize is a generator yielding...    parameter:f contains...
        level = 0
    for line, src in enumerate(f):
```

also, maybe using longer names for variables will make the code more readable, e.g. why "f" and not "source"?  "f" is "source"?

**Comment by djc** [comment]
Thanks for all the feedback! I've been very focused on actually implementing the compiler so far, since I don't think design documentation on its own is very interesting. However, better documentation is now near the top of my to do list (along with exception support). I've actually been working on a Sphinx-generated documentation site recently, which I'll hopefully put up soon. I'll try to include a more elaborate rationale there.

In the mean time, I've started by adding a short top-level introduction to the README in 1eaedd45. I've also added module-level comments to most modules, and function- or class-level comments to the others. If you have any more specific qestions about the design or the implementation, let me know, and I'll write more comments/documentation.

**Comment by djc** [comment]
The Sphinx site is online now, at http://runa-lang.org/. Will work on some rationale soon.

**Comment by djc** [comment]
I've finally added a rationale to the documentation. I've also been adding a bunch of comments over the past months, hopefully the code should be a bit easier to follow. I'll continue to add some design goals and roadmap to the high-level overview in the documentation, please let me know if there's still stuff missing that you would be interested to see.
