### ISSUE TITLE
Why "spaces indentation is not supported"?

### ISSUE THREAD

**Issue by luciotato** [djc/runa#2]
Sounds strange to me. 
can you tell me how difficult it will be to support spaces as indentation?

**Comment by djc** [comment]
It wouldn't be too hard, relative to other implementation tasks.

However, at this point I'm leaning towards not implementing it at all. I've updated the README in 2e0c448 to not waffle about it so much. The reason for this is that I think it's clear that Python's mixed mode, where both tabs and spaces are allowed, makes things harder. In the choice of tabs versus spaces, tabs seem to be a better fit for indentation, simply because that's what they were designed for. I also like the fact that the use of tabs allows people to use different tab sizes as they see fit.

Go is an example of a language mandating tabs for indentation (through `go fmt`), so I don't think this a bad choice, although it's perhaps slightly incongruous with the desire to be easy for Python developers to pick up. However, I think that would mostly be resolved by setting up editors correctly.

Thanks for the feedback!
